# Imports
from utils import *


# Metadatas
ARGUMENTS["platform_type"] = ARGUMENTS.get("platform_type", "Server")
ARGUMENTS["build_type"] = ARGUMENTS.get("build_type", "Debug")


# Environments
cwd = os.path.abspath(os.getcwd())
env = Environment(tools=["default", "msvc"], PLATFORM="")
env.BuildConan(ARGUMENTS["build_type"])
env.MergeFlags(SConscript(".conan/SConscript_conandeps")["conandeps"])
env.sources = (
    env.RGlob("Type", "*.cpp") + 
    env.RGlob("System", "*.cpp") + 
    env.RGlob("Sandbox", "*.cpp") + 
    env.RGlob("Vendor", "*.cpp") + 
    env.RGlob("Vendor", "*.c") + 
    env.RGlob("Vendor", "*.cc")
)
env.Append(CPPPATH=[
    cwd,
    os.path.join(cwd, "Type"),
    os.path.join(cwd, "System"),
    os.path.join(cwd, "Sandbox"),
    os.path.join(cwd, "Vendor"),
    os.path.join(cwd, "Vendor/fmt"),
    os.path.join(cwd, "Vendor/msgpack"),
    os.path.join(cwd, "Vendor/rapidjson"),
    os.path.join(cwd, "Vendor/lua"),
    os.path.join(cwd, "Vendor/duktape")
])
env.BuildVCPKG()


# Flags
if ARGUMENTS["platform_type"] == "Client":
    env.Append(CPPDEFINES=["Vital_SDK_Client"])


# Dependencies
env.Append(CPPDEFINES=["MSGPACK_NO_BOOST"])
if sys.platform.startswith("win"):
    env.Append(CPPDEFINES=["Vital_SDK_WINDOWS"])
    env.Append(CPPFLAGS=["/EHsc"])
    env.Append(LIBS=["ws2_32", "winmm", "wbemuuid"])
elif sys.platform == "darwin":
    env.Append(CPPDEFINES=["Vital_SDK_MACOS"])
    env.Append(CPPDEFINES=["LUA_USE_MACOSX", "DUK_F_APPLE"])
elif sys.platform.startswith("linux"):
    env.Append(CPPDEFINES=["Vital_SDK_LINUX"])
    env.Append(CPPDEFINES=["LUA_USE_LINUX", "DUK_F_LINUX"])

    
# Returns
Return("env")