# Imports
from vital import *


# Environment
os_info = Fetch_OS()
cwd = os.path.abspath(os.getcwd())
env = Environment(tools=Fetch_Compiler(), PLATFORM="")
env.name = "vital.sdk"
env.Args = ARGUMENTS
env.Args["platform_type"] = env.Args.get("platform_type", "Server")
env.Args["build_type"] = env.Args.get("build_type", "Debug")


# Flags
env.Module.build()
env.MergeFlags(SConscript(".conan/SConscript_conandeps")["conandeps"])

if env.Args["platform_type"] == "Client":
    env.Append(CPPDEFINES=["Vital_SDK_Client"])

if os_info["type"] == "Windows":
    env.Append(CPPDEFINES=["Vital_SDK_WINDOWS"])
    env.Append(CPPDEFINES=["_WIN32_WINNT=0x0A00", "WINVER=0x0A00", "WIN32_LEAN_AND_MEAN", "NOMINMAX"])
    env.Append(CPPFLAGS=["/EHsc", "/wd4244", "/MD"])
    env.Append(LIBS=["ws2_32", "winmm", "wbemuuid"])
    env.Append(LINKFLAGS=["/NODEFAULTLIB:LIBCMT", "/NODEFAULTLIB:LIBCMTD", "/NODEFAULTLIB:MSVCRTD"])
elif os_info["type"] == "Darwin":
    env.Append(CPPDEFINES=["Vital_SDK_MACOS"])
    env.Append(CPPDEFINES=["LUA_USE_MACOSX", "DUK_F_APPLE", "HAS_SOCKLEN_T"])
elif os_info["type"] == "Linux":
    env.Append(CPPDEFINES=["Vital_SDK_LINUX"])
    env.Append(CPPDEFINES=["LUA_USE_LINUX", "DUK_F_LINUX", "HAS_SOCKLEN_T"])
    env.Append(CXXFLAGS=["-fexceptions"])


# Sandbox
env = SConscript("Vendor/godot-cpp/SConstruct", {"env": env.Clone()})
vendor_exclude = [
    "Vendor/godot-cpp"
]
env.sources = (
    env.RGlob("Tool", "*.cpp") +
    env.RGlob("Sandbox", "*.cpp") +
    env.RGlob("Engine", "*.cpp") +
    env.RGlob("Manager", "*.cpp") +
    env.RGlob("System", "*.cpp") +
    env.RGlob("Vendor", "*.cpp", exclude=vendor_exclude) +
    env.RGlob("Vendor", "*.c",   exclude=vendor_exclude) +
    env.RGlob("Vendor", "*.cc",  exclude=vendor_exclude)
)
env.Append(CPPPATH=[
    cwd,
    os.path.join(cwd, ".."),
    os.path.join(cwd, "Tool"),
    os.path.join(cwd, "Sandbox"),
    os.path.join(cwd, "Engine"),
    os.path.join(cwd, "Manager"),
    os.path.join(cwd, "System"),
    os.path.join(cwd, "Vendor"),
    os.path.join(cwd, "Vendor/lua"),
    os.path.join(cwd, "Vendor/discord-sdk")
])


# Build
platform = env["platform"]
build_dir = f".build/{env.Args['platform_type'].lower()}/{platform}"
bin_dir = (
    f".bin/{env.Args['platform_type'].lower()}/{platform}/"
    f"{env.name}"
    f"{env['suffix'].replace('.dev','').replace('.universal','').replace(f'.{platform}','').replace('template_','')}"
    f"{env.subst('$SHLIBSUFFIX')}"
)
bin = env.SharedLibrary(bin_dir, source=env.sources)
build = env.Install(build_dir, bin)
env.Module.stage(build)
Default([bin, build])
