# Imports
import sys
sys.path.append("../Vital.sandbox")
from vital import *


# Metadatas
name = "vital.sdk"
ARGUMENTS["target"] = f"template_{ARGUMENTS["build_type"].lower()}" 
ARGUMENTS["use_static_cpp"] = "no" 


# Environments
os_info = Fetch_OS()
cwd = os.path.abspath(os.getcwd())
env = SConscript("../Vital.sandbox/SConstruct")
env = SConscript("Vendor/godot/SConstruct", {"env": env.Clone()})
env.sources += (
    env.RGlob("Engine", "*.cpp") + 
    env.RGlob("Engine", "*.c") + 
    env.RGlob("Sandbox", "*.cpp") + 
    env.RGlob("Sandbox", "*.c")
)
env.Append(CPPPATH=[
    cwd,
    os.path.join(cwd, "../"),
    os.path.join(cwd, "Engine"),
    os.path.join(cwd, "Sandbox"),
    os.path.join(cwd, "Vendor")
])


# Flags
if os_info["type"] == "Windows":
    env.Append(LINKFLAGS=["/NODEFAULTLIB:LIBCMTD", "/NODEFAULTLIB:MSVCRTD"])
else:
    env.Append(CXXFLAGS=["-fexceptions"])


# Builds
build_dir = f".build/{name}/{env['platform']}"
bin_dir = f".bin/{env['platform']}/{name}{env['suffix'].replace('.dev','').replace('.universal','').replace(f'.{env['platform']}','').replace('template_','')}{env.subst('$SHLIBSUFFIX')}"
bin = env.SharedLibrary(bin_dir, source = env.sources)
build = env.Install(build_dir, bin)
env.Stage_Module(build)
Default([bin, build])